name: icecap
channels:
  - conda-forge
dependencies:
  - python=3.13
  - cartopy
  - cdsapi
  - cfgrib
  - cmocean
  - dask
  - eccodes
  - ecflow
  - ipykernel
  - ipython
  - ipywidgets
  - matplotlib
  - netcdf4=1.7.4
  - numpy
  - pandas
  - scipy
  - xarray
  - xesmf
  - xskillscore
  - jupyterlab
  - jupytext

